name: CI

on:
  push:
  pull_request:

jobs:
  markdown:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mdformat
        run: |
          pip install mdformat==1.0.0 mdformat-gfm==1.0.0 mdformat_frontmatter==2.1.2
          mdformat --version

<<<<<<< Updated upstream
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: README.md
          fail: true
||||||| Stash base
     - name: Check links
       uses: lycheeverse/lychee-action@v2
       with:
         args: README.md
         fail: true
=======
     - name: Check links
       uses: lycheeverse/lychee-action@v2
       with:
         args: README.md
         fail: false
>>>>>>> Stashed changes

      - name: Lint file
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: README.md
        continue-on-error: true
