name: CI

on:
  push:
  pull_request:

jobs:
  markdown:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mdformat
        run: |
          pip install mdformat==1.0.0
          mdformat --version

      - name: Check formatting
        run: mdformat --check README.md
