name: CI

on:
  push:
  pull_request:

jobs:
  markdown:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mdformat
        run: |
          pip install mdformat==1.0.0 mdformat-gfm==1.0.0 mdformat_frontmatter==2.1.2
          mdformat --version

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: Install lychee
        run: |
          cargo install lychee
          lychee --version

      - name: Check formatting
        run: mdformat --check README.md
        
      - name: Lint file
        run: markdownlint-cli2 README.md
        
      - name: Check links
        run: lychee README.md
